// supabase/functions/extract-youtube/index.ts
// YouTube → 블로그 변환 Edge Function
//
// 요청:  POST /functions/v1/extract-youtube
//        Authorization: Bearer <supabase_jwt>
//        Content-Type:  application/json
//        Body: { videoUrl: string, options?: TransformOptions }
//
// 성공:  { ok: true, data: { transcript: {...}, blogPost: {title, content, tokensUsed, model, finishReason}, source: {...}, quota: {...} } }
// 실패:  { ok: false, error: { code, message, details? } }
//
// 처리 순서:
//   1) OPTIONS preflight
//   2) 메서드 / Content-Type 검증
//   3) JWT 검증 → profiles 조회
//   4) 입력 파싱 + videoUrl 검증
//   5) 쿼터 체크 (extract_youtube)
//   6) YouTube 자막 fetch
//   7) Gemini 로 블로그 변환
//   8) usage_logs 기록
//   9) 응답
//
// 참조: edge_function_contracts.md §2 (본 파일 완료 후 업데이트)

import { serve } from 'https://deno.land/std@0.220.0/http/server.ts'

import { authenticate, authErrorResponse } from '../_shared/auth.ts'
import {
  checkQuota,
  recordUsage,
  quotaErrorResponse,
  type Feature
} from '../_shared/usage.ts'
import { geminiErrorResponse, isGeminiError } from '../_shared/gemini.ts'
import {
  extractVideoId,
  fetchTranscript,
  isYoutubeError,
  youtubeErrorResponse
} from '../_shared/youtube.ts'
import {
  transformTranscriptToBlog,
  type TransformOptions
} from '../_shared/blog-transform.ts'
import { corsHeaders, handleOptions } from '../generate-content/cors.ts'

const FEATURE: Feature = 'extract_youtube'

type RequestBody = {
  videoUrl?: unknown
  options?: unknown
}

serve(async (req: Request): Promise<Response> => {
  const cors = corsHeaders(req)

  // 1) Preflight
  if (req.method === 'OPTIONS') return handleOptions(req)

  // 2) 메서드 / Content-Type
  if (req.method !== 'POST') {
    return errorResponse('method_not_allowed', 'POST 요청만 허용됩니다.', 405, cors)
  }
  const contentType = req.headers.get('Content-Type') ?? ''
  if (!contentType.toLowerCase().includes('application/json')) {
    return errorResponse('invalid_content_type', 'Content-Type 은 application/json 이어야 합니다.', 415, cors)
  }

  // 3) 인증
  let ctx
  try {
    ctx = await authenticate(req)
  } catch (err) {
    return authErrorResponse(err, cors)
  }

  // 4) 입력 파싱
  let videoUrl: string
  let options: TransformOptions
  try {
    const parsed = await parseBody(req)
    videoUrl = parsed.videoUrl
    options = parsed.options
  } catch (err) {
    const msg = err instanceof Error ? err.message : '요청 본문을 해석할 수 없습니다.'
    return errorResponse('invalid_input', msg, 400, cors)
  }

  const videoId = extractVideoId(videoUrl)
  if (!videoId) {
    return errorResponse(
      'invalid_url',
      '지원하는 YouTube URL 형식이 아닙니다. (예: https://www.youtube.com/watch?v=..., https://youtu.be/..., /shorts/...)',
      400,
      cors
    )
  }

  // 5) 쿼터 체크 (YouTube fetch 전에 차단 — 외부 요청 비용 발생 방지)
  const quota = await checkQuota(ctx.supabase, ctx.profile, FEATURE)
  if (!quota.allowed) {
    return quotaErrorResponse(quota, cors)
  }

  // 6) Transcript fetch
  let transcript
  try {
    transcript = await fetchTranscript(videoId)
  } catch (err) {
    if (isYoutubeError(err)) {
      console.warn('[extract-youtube] transcript failed', {
        userId: ctx.userId, videoId, code: err.code
      })
      return youtubeErrorResponse(err, cors)
    }
    console.warn('[extract-youtube] transcript unknown error', { userId: ctx.userId, videoId })
    return errorResponse(
      'upstream_error',
      '자막을 가져오는 중 알 수 없는 오류가 발생했습니다.',
      502,
      cors
    )
  }

  // 7) Gemini 변환
  let blogPost
  try {
    blogPost = await transformTranscriptToBlog(
      transcript.text,
      {
        videoId: transcript.videoId,
        title: transcript.title,
        author: transcript.author,
        durationSec: transcript.durationSec,
        language: transcript.language
      },
      {
        targetLanguage:
          (options.targetLanguage ??
            (ctx.profile.language as TransformOptions['targetLanguage']) ??
            'ko'),
        length: options.length
      }
    )
  } catch (err) {
    if (isGeminiError(err)) {
      console.warn('[extract-youtube] gemini failed', {
        userId: ctx.userId, videoId, code: err.code, httpStatus: err.httpStatus
      })
    } else {
      console.warn('[extract-youtube] gemini unknown error', { userId: ctx.userId, videoId })
    }
    return geminiErrorResponse(err, cors)
  }

  // 8) usage_logs 기록 — 최종 성공 경로에서만
  await recordUsage(ctx.supabase, ctx.userId, FEATURE, blogPost.tokensUsed)

  // 9) 응답 — transcript.segments 는 용량 우려로 제외. 클라이언트는 text 만 사용.
  return jsonResponse(
    {
      ok: true,
      data: {
        transcript: {
          videoId: transcript.videoId,
          language: transcript.language,
          isAutoGenerated: transcript.isAutoGenerated,
          text: transcript.text,
          charCount: transcript.text.length
        },
        blogPost: {
          title: blogPost.title,
          content: blogPost.content,
          tokensUsed: blogPost.tokensUsed,
          model: blogPost.model,
          finishReason: blogPost.finishReason
        },
        source: {
          videoId: transcript.videoId,
          title: transcript.title,
          author: transcript.author,
          durationSec: transcript.durationSec,
          url: `https://www.youtube.com/watch?v=${transcript.videoId}`
        },
        quota: {
          minuteCount: quota.minuteCount + 1,
          dailyCount: quota.dailyCount + 1,
          dailyQuota: isFinite(quota.dailyQuota) ? quota.dailyQuota : null,
          minuteLimit: quota.minuteLimit
        }
      }
    },
    200,
    cors
  )
})

// -----------------------------------------------------------------------------
// Body parsing
// -----------------------------------------------------------------------------

async function parseBody(
  req: Request
): Promise<{ videoUrl: string; options: TransformOptions }> {
  let raw: unknown
  try {
    raw = await req.json()
  } catch {
    throw new Error('요청 본문을 JSON 으로 해석할 수 없습니다.')
  }
  if (!isObject(raw)) throw new Error('요청 본문이 객체가 아닙니다.')
  const body = raw as RequestBody

  if (typeof body.videoUrl !== 'string' || body.videoUrl.trim().length === 0) {
    throw new Error('videoUrl 은 비어있지 않은 문자열이어야 합니다.')
  }
  const videoUrl = body.videoUrl.trim()
  if (videoUrl.length > 500) {
    throw new Error('videoUrl 은 500자 이하여야 합니다.')
  }

  return { videoUrl, options: parseOptions(body.options) }
}

function parseOptions(raw: unknown): TransformOptions {
  if (!isObject(raw)) return {}
  const o = raw as Record<string, unknown>
  const out: TransformOptions = {}
  if (o.targetLanguage === 'ko' || o.targetLanguage === 'en' || o.targetLanguage === 'ja') {
    out.targetLanguage = o.targetLanguage
  }
  if (o.length === 'short' || o.length === 'normal' || o.length === 'long') {
    out.length = o.length
  }
  return out
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

// -----------------------------------------------------------------------------
// Response helpers
// -----------------------------------------------------------------------------

function jsonResponse(body: unknown, status: number, cors: Record<string, string>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...cors }
  })
}

function errorResponse(
  code: string,
  message: string,
  status: number,
  cors: Record<string, string>
): Response {
  return jsonResponse({ ok: false, error: { code, message } }, status, cors)
}
